fix: clean notebook output before running tests & tweak doc proc notebook (#5055)
## Changes Made

- CI: uses `nb-clean` to remove all notebook output before running.
- Tweaks to document processing tutorial notebook:
+ `CI: bool` is now a notebook parameter, so `papermill -p CI true`
works
  + `if CI` then writes output to temporary directory
+ global var for embedding model name + dimensionality: TextEmbedderUdf
init check to ensure dims match, fail fast
+ text embedder UDF always takes device: notebook auto selects best
device
  + use `mps` device on OS X as it's faster than CPU

## Related Issues

Running into a weird issue running the document processing notebook in
Python 3.9. The error is `AttributeError: 'TracebackException' object
has no attribute 'exceptions'`. According to the std lib docs
(https://docs.python.org/3/library/traceback.html#traceback.TracebackException.exceptions),
this attribute was introduced in 3.11. Somehow, its trying to access a
3.11 feature in 3.9. The intention here is that by cleaning the notebook
before running there will be no leftovers from the last time it was
executed & checked-in.