[Bug] Empty struct arrays (no fields) (#858)
# Summary

Empty struct arrays (with no fields!) are currently broken.

## Problem

**Problem 1**

Our logic for `_propagate_array_slice_offsets` currently returns a
length 0 StructArray when it has no fields, causing errors that look
like:

```
pyarrow.lib.ArrowInvalid: Added column's length must match table's length. Expected length 2 but got length 0
```

**Problem 2**

Creating Series from these arrays makes `arrow2::ffi` very unhappy,
causing errors that look like:

```
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: OutOfSpec("A StructArray must contain at least one field")
```

Both these issues are reproducible by running the failing test on this
PR: `pytest tests/table/test_from_py.py`

## Solution

1. We detect any Pyarrow datastructures with empty structs on Table and
Series construction, dynamically converting them into `{"": Null}` types
instead before it ever hits our Rust layer.
2. As a drive-by, this PR also unifies this code with our Offset-fixing
code into the `arrow_utils.ensure_array`,
`arrow_utils.ensure_chunked_array`, `arrow_utils.ensure_table`
functions, which will apply all the patches we need whenever we have
PyArrow data coming through our system...

---------

Co-authored-by: Jay Chia <jaychia94@gmail.com@users.noreply.github.com>
Co-authored-by: Clark Zinzow <clarkzinzow@gmail.com>