feat: retryable udfs (#5392)
## Changes Made

currently only implemented for rowwise scalar udf. 

TODO: the error message could be a bit better as the row index is kinda
useless without being able to correlate it back to a batch.



example usage
```py
image_tensor = np.random.randint(0, 256, (224, 224, 3), dtype=np.uint8)
images = [image_tensor] * 10_000
df = daft.from_pydict({"images": images})


@daft.func(use_process=True, return_dtype=daft.DataType.image(), max_retries=3, on_error="raise")
def random_fail(x):
    # Randomly fail approximately 20% of the time
    if random.random() < 0.2:
        raise ValueError("Random failure in processing")
    return x


print(df.select(random_fail(df["images"])).collect())
```

```
daft.exceptions.DaftCoreException: DaftError::ComputeError Failed to execute Python UDF on some rows
: 	
	746: DaftError::PyO3Error ValueError: Random failure in processing
	1171: DaftError::PyO3Error ValueError: Random failure in processing
	1791: DaftError::PyO3Error ValueError: Random failure in processing
	1831: DaftError::PyO3Error ValueError: Random failure in processing
	2263: DaftError::PyO3Error ValueError: Random failure in processing
	2364: DaftError::PyO3Error ValueError: Random failure in processing
	2896: DaftError::PyO3Error ValueError: Random failure in processing
	3030: DaftError::PyO3Error ValueError: Random failure in processing
	3342: DaftError::PyO3Error ValueError: Random failure in processing
	3484: DaftError::PyO3Error ValueError: Random failure in processing
	4389: DaftError::PyO3Error ValueError: Random failure in processing
	4600: DaftError::PyO3Error ValueError: Random failure in processing
	4936: DaftError::PyO3Error ValueError: Random failure in processing
	5018: DaftError::PyO3Error ValueError: Random failure in processing
	6056: DaftError::PyO3Error ValueError: Random failure in processing
	7825: DaftError::PyO3Error ValueError: Random failure in processing
	8853: DaftError::PyO3Error ValueError: Random failure in processing
	9291: DaftError::PyO3Error ValueError: Random failure in processing
	9609: DaftError::PyO3Error ValueError: Random failure in processing
```

## Related Issues

<!-- Link to related GitHub issues, e.g., "Closes #123" -->

## Checklist

- [ ] Documented in API Docs (if applicable)
- [ ] Documented in User Guide (if applicable)
- [ ] If adding a new documentation page, doc is added to
`docs/mkdocs.yml` navigation
- [ ] Documentation builds and is formatted properly

---------

Co-authored-by: Colin Ho <colin.ho99@gmail.com>