[FEAT] Add more context when UDFs fail (#2325)
This PR adds some context around failures of UDFs, and also has the
side-effect of quite nicely isolating the actual exception to just the
UDF code so users can be sure that the code failed in the UDF rather
than in some part of Daft.

```
In [4]: daft.from_pydict({"foo": [1]}).with_column("identity", throws_error_if_len_1(daft.col("foo"))).collect()
Project [Stage:2]:   0%|                                                                                                    | 0/1 [00:00<?, ?it/s]---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File ~/code/Daft/daft/udf.py:108, in PartialUDF.__call__(self, evaluated_expressions)
    107 try:
--> 108     result = func(*args, **kwargs)
    109 except Exception as user_function_exception:

Cell In[2], line 4, in throws_error_if_len_1(data)
      3 if len(data) == 1:
----> 4     raise ValueError("I hate len 1 data")
      5 else:

ValueError: I hate len 1 data

The above exception was the direct cause of the following exception:

... 

RuntimeError                              Traceback (most recent call last)
...
File ~/code/Daft/daft/udf.py:110, in PartialUDF.__call__(self, evaluated_expressions)
    108     result = func(*args, **kwargs)
    109 except Exception as user_function_exception:
--> 110     raise RuntimeError(f"User-defined function `{func.__name__}` failed when executing on inputs with lengths: {tuple(len(series) for series in evaluated_expressions)}") from user_function_exception
    112 # HACK: Series have names and the logic for naming fields/series in a UDF is to take the first
    113 # Expression's name. Note that this logic is tied to the `to_field` implementation of the Rust PythonUDF
    114 # and is quite error prone! If our Series naming logic here is wrong, things will break when the UDF is run on a table.
    115 name = evaluated_expressions[0].name()

RuntimeError: User-defined function `throws_error_if_len_1` failed when executing on inputs with lengths: (1,)
```

---------

Co-authored-by: Jay Chia <jaychia94@gmail.com@users.noreply.github.com>