fix: Format nested Rust errors as a simplified backtrace in Python (#7178)
## Changes Made

I was getting annoyed by the long Rust error messages we print in
Python. For example, when we missing AWS SSO credentials and access some
file, we get the following Python exception:

```
DaftCoreException: DaftError::External Unable to load Credentials for store: s3
Details:
ProviderError(ProviderError { source: ProviderError(ProviderError { source: ServiceError(ServiceError { source: UnauthorizedException(UnauthorizedException { message: Some("Session token not found or invalid"), meta: ErrorMetadata { code: Some("UnauthorizedException"), message: Some("Session token not found or invalid"), extras: Some({"aws_request_id": "..."}) } }), raw: Response { status: StatusCode(401), headers: Headers { headers: {"date": HeaderValue { _private: H1("...") }, "content-type": HeaderValue { _private: H1("application/json") }, "content-length": HeaderValue { _private: H1("114") }, "access-control-expose-headers": HeaderValue { _private: H1("RequestId") }, "access-control-expose-headers": HeaderValue { _private: H1("x-amzn-RequestId") }, "requestid": HeaderValue { _private: H1("...") }, "server": HeaderValue { _private: H1("AWS SSO") }, "x-amzn-requestid": HeaderValue { _private: H1("...") }} }, body: SdkBody { inner: Once(Some(b"{\"message\":\"Session token not found or invalid\",\"__type\":\"com.amazonaws.switchboard.portal#UnauthorizedException\"}")), retryable: true }, extensions: Extensions { extensions_02x: Extensions, extensions_1x: {hyper_util::client::legacy::connect::http::HttpInfo} } } }) }) })
```

This PR formats it into:

```
DaftCoreException: Unable to load credentials for IO backend `s3`

Caused by the following errors:
  1: an error occurred while loading credentials
  2: service error
  3: UnauthorizedException: Session token not found or invalid
```

Inspired by the report formatting in
https://docs.rs/snafu/latest/snafu/, and may improve it to look more
like https://docs.rs/miette/latest/miette in a later PR.

---------

Co-authored-by: greptile-apps[bot] <165735046+greptile-apps[bot]@users.noreply.github.com>