fix: Add outer try-finally block in executor generator (#5633)
## Changes Made

fixes the `no_running_event_loop errors`

```
tests/dataframe/test_show_limit.py::test_show_limit_n_plain_counts_rows
  /home/runner/work/Daft/Daft/.venv/lib/python3.13/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <async_generator object NativeExecutor.run.<locals>.run_executor at 0x7f29ca809fc0>
  
  Traceback (most recent call last):
    File "/home/runner/work/Daft/Daft/daft/execution/native_executor.py", line 58, in run_executor
      yield batch
  GeneratorExit
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/home/runner/work/Daft/Daft/daft/execution/native_executor.py", line 60, in run_executor
      _ = await result_handle.finish()
                ~~~~~~~~~~~~~~~~~~~~^^
  RuntimeError: no running event loop
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
```

## Related Issues

Closes https://github.com/Eventual-Inc/Daft/issues/5636

## Checklist

- [ ] Documented in API Docs (if applicable)
- [ ] Documented in User Guide (if applicable)
- [ ] If adding a new documentation page, doc is added to
`docs/mkdocs.yml` navigation
- [ ] Documentation builds and is formatted properly