chore: improve the stability of unit test (#4565)
## Changes Made


## Related Issues

improve some test cases describe in
https://github.com/Eventual-Inc/Daft/discussions/4564

```
FAILED tests/io/test_s3_credentials_refresh.py::test_s3_credentials_refresh - botocore.errorfactory.BucketAlreadyOwnedByYou: An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operati...

FAILED tests/io/test_url_upload_local.py::test_upload_local_no_write_permissions - Failed: DID NOT RAISE <class 'daft.exceptions.DaftCoreException'>

FAILED tests/recordbatch/numeric/test_numeric.py::test_table_numeric_trigonometry[sinh-False-False] - assert False is True

FAILED tests/recordbatch/numeric/test_numeric.py::test_table_numeric_trigonometry[cosh-False-False] - assert False is True

FAILED tests/recordbatch/numeric/test_numeric.py::test_table_numeric_trigonometry[arccos-True-False] - assert False is True
```

## Checklist

- [ ] Documented in API Docs (if applicable)
- [ ] Documented in User Guide (if applicable)
- [ ] If adding a new documentation page, doc is added to
`docs/mkdocs.yml` navigation
- [ ] Documentation builds and is formatted properly (tag @/ccmao1130
for docs review)

Co-authored-by: wuzhiping <wuzhiping.007@bytedance.com>