[CHORE] add ray client to deps (#1631)
failure when running on remote clusters:
```
  File "/runner/_work/daft-benchmarking/daft-benchmarking/.venv/lib/python3.10/site-packages/ray/client_builder.py", line 99, in __init__
    raise ValueError(
ValueError: Ray Client requires pip package `ray[client]`. If you installed the minimal Ray (e.g. `pip install ray`), please reinstall by executing `pip install ray[client]`.
```