fix: overriding dimensions for openai embedding models (#6013)
## Changes Made

When overriding the embedding dimension to `embed_text` with the OpenAI
provider, it would fail with this message:
```
daft.exceptions.DaftTypeError: Can not cast Tensor array to FixedShapeTensor array with type FixedShapeTensor(Float32, [256]): Tensor array has shapes different than [256];
```

This was because we were only passing in the dimensions when
`embed_options["supports_overriding_dimensions"]` was true, but that was
not set, even though we hardcoded the support in the `_models` variable.

This PR sets the `supports_overriding_dimensions` option when the OpenAI
model supports it, fixing the issue.

## Related Issues

<!-- Link to related GitHub issues, e.g., "Closes #123" -->