[CHORE] Improve swordfish error handling (#2628)
This PR adds functionality to properly raise errors from tasks in the
native executor. This works by:
- Spawning all tokio tasks on an `ExecutionRuntimeHandle`, which is a
wrapper around a JoinSet. This allows us to join on the tasks and short
circuit execution upon a task returning with an error.
- Refactoring Sources accept a sender + runtime handle so that it can
spawn tasks within it's `get_data` method

Example error:
```
df = daft.from_pydict({"a": ["foo", "bar", "baz"]})
df = df.select(df["a"].str.match("["))
df.show()
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    df.show()
  File "/Users/colinho/Desktop/Daft/daft/api_annotations.py", line 26, in _wrap
    return timed_method(*args, **kwargs)
  File "/Users/colinho/Desktop/Daft/daft/analytics.py", line 185, in tracked_method
    return method(*args, **kwargs)
  File "/Users/colinho/Desktop/Daft/daft/dataframe/dataframe.py", line 2219, in show
    dataframe_display = self._construct_show_display(n)
  File "/Users/colinho/Desktop/Daft/daft/dataframe/dataframe.py", line 2176, in _construct_show_display
    for table in get_context().runner().run_iter_tables(builder, results_buffer_size=1):
  File "/Users/colinho/Desktop/Daft/daft/runners/pyrunner.py", line 216, in run_iter_tables
    for result in self.run_iter(builder, results_buffer_size=results_buffer_size):
  File "/Users/colinho/Desktop/Daft/daft/runners/pyrunner.py", line 197, in run_iter
    results_gen = executor.run(
  File "/Users/colinho/Desktop/Daft/daft/execution/native_executor.py", line 33, in run
    PyMaterializedResult(MicroPartition._from_pymicropartition(part)) for part in self._executor.run(psets_mp)
daft.exceptions.DaftCoreException: DaftError::ValueError regex parse error:
    [
    ^
error: unclosed character class
```
str.match is a regex match function, "[" is an invalid regex that causes
a runtime error

---------

Co-authored-by: Colin Ho <colinho@Colins-MBP.localdomain>