Fix self join where column name can conflict (#521)
Fixes bug in self join where we get a key error when we join two
dataframes that have name conflict for the non join keys
```
    daft_df = daft_df.select(col("Unique Key"), col("Borough"))
    daft_df = daft_df.join(daft_df, col("Unique Key"))
```
would yield:
```
/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/daft/runners/partitioning.py in eval_expression(self, expr)
    198         required_blocks = {}
    199         for name in required_cols:
--> 200             block = self.columns[name].block
    201             required_blocks[name] = block
    202         exec = ExpressionExecutor()

KeyError: 'right.Borough'
```