fix: Executing `explain` will panic when ScanTask is empty (#5582)
## Changes Made

<!-- Describe what changes were made and why. Include implementation
details if necessary. -->

Fix the issue where a painc error would occur when running
`explain(show_all=True)` in on-ray mode if ScanTask was empty, for
example:

```python
# export DAFT_RUNNER=ray

df = daft.read_lance(url="/tmp/lance").limit(0)
df.explain(show_all=True)
```

Then will report the following error:

```text
thread '<unnamed>' (3141581) panicked at src/daft-distributed/src/pipeline_node/scan_source.rs:159:32:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/opt/workspace/github/daft-examples/test.py", line 42, in <module>
    df.explain(show_all=True)
  File "/opt/workspace/github/daft-examples/.venv/lib/python3.12/site-packages/daft/api_annotations.py", line 32, in _wrap
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/workspace/github/daft-examples/.venv/lib/python3.12/site-packages/daft/dataframe/dataframe.py", line 293, in explain
    print_to_file(distributed_plan.repr_ascii(simple))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: index out of bounds: the len is 0 but the index is 0
```

## Related Issues

<!-- Link to related GitHub issues, e.g., "Closes #123" -->

## Checklist

- [ ] Documented in API Docs (if applicable)
- [ ] Documented in User Guide (if applicable)
- [ ] If adding a new documentation page, doc is added to
`docs/mkdocs.yml` navigation
- [ ] Documentation builds and is formatted properly

Signed-off-by: plotor <zhenchao.wang@hotmail.com>